// AUTO-GENERATED by scripts/generate-puzzles.js — do not edit by hand.
// Each study has start + goal arrangements on a 3x3 board; "par" is the
// BFS-verified minimum number of moves.
export const LEVELS = [
  {
    "id": "aprendiz",
    "name": "Aprendiz",
    "puzzles": [
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "par": 3
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "par": 3
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "par": 3
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "par": 3
      }
    ]
  },
  {
    "id": "maestro",
    "name": "Maestro",
    "puzzles": [
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 3
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 5
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "par": 6
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 0
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "par": 6
      }
    ]
  },
  {
    "id": "granmaestro",
    "name": "Gran Maestro",
    "puzzles": [
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "par": 5
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "par": 5
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "B",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "par": 5
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 5
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "par": 5
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 4
      }
    ]
  }
];
