// AUTO-GENERATED by scripts/generate-puzzles.js — do not edit by hand.
// Each study is verified solvable; "par" is the minimum number of moves.
export const LEVELS = [
  {
    "id": "aprendiz",
    "name": "Aprendiz",
    "puzzles": [
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "R",
            "c": 3,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 3,
            "r": 0
          },
          {
            "type": "Q",
            "c": 1,
            "r": 3
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "Q",
            "c": 2,
            "r": 0
          },
          {
            "type": "B",
            "c": 3,
            "r": 1
          },
          {
            "type": "N",
            "c": 3,
            "r": 2
          },
          {
            "type": "Q",
            "c": 0,
            "r": 0
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "P",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 1,
            "r": 3
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "R",
            "c": 1,
            "r": 3
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "P",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 3
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "P",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 3
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "N",
            "c": 3,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          }
        ],
        "par": 3
      },
      {
        "cols": 4,
        "rows": 4,
        "pieces": [
          {
            "type": "B",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "Q",
            "c": 1,
            "r": 1
          }
        ],
        "par": 3
      }
    ]
  },
  {
    "id": "maestro",
    "name": "Maestro",
    "puzzles": [
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "R",
            "c": 4,
            "r": 1
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "B",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 3,
            "r": 3
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "P",
            "c": 4,
            "r": 3
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "Q",
            "c": 3,
            "r": 2
          },
          {
            "type": "P",
            "c": 4,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 3
          },
          {
            "type": "B",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 3,
            "r": 1
          },
          {
            "type": "Q",
            "c": 4,
            "r": 2
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 3,
            "r": 3
          },
          {
            "type": "Q",
            "c": 2,
            "r": 4
          },
          {
            "type": "P",
            "c": 4,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 3
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "N",
            "c": 4,
            "r": 2
          },
          {
            "type": "P",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 3
          },
          {
            "type": "B",
            "c": 3,
            "r": 3
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "B",
            "c": 0,
            "r": 4
          },
          {
            "type": "Q",
            "c": 4,
            "r": 2
          },
          {
            "type": "P",
            "c": 3,
            "r": 1
          }
        ],
        "par": 4
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 4,
            "r": 1
          },
          {
            "type": "B",
            "c": 4,
            "r": 4
          },
          {
            "type": "Q",
            "c": 3,
            "r": 0
          }
        ],
        "par": 4
      }
    ]
  },
  {
    "id": "granmaestro",
    "name": "Gran Maestro",
    "puzzles": [
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 4
          },
          {
            "type": "R",
            "c": 1,
            "r": 3
          },
          {
            "type": "B",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 3,
            "r": 3
          },
          {
            "type": "P",
            "c": 3,
            "r": 2
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "K",
            "c": 4,
            "r": 3
          },
          {
            "type": "N",
            "c": 3,
            "r": 2
          },
          {
            "type": "B",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 3,
            "r": 0
          },
          {
            "type": "B",
            "c": 3,
            "r": 3
          },
          {
            "type": "N",
            "c": 3,
            "r": 1
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "P",
            "c": 4,
            "r": 3
          },
          {
            "type": "N",
            "c": 0,
            "r": 4
          },
          {
            "type": "B",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "Q",
            "c": 3,
            "r": 4
          },
          {
            "type": "Q",
            "c": 0,
            "r": 2
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "R",
            "c": 1,
            "r": 4
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "Q",
            "c": 3,
            "r": 3
          },
          {
            "type": "B",
            "c": 2,
            "r": 4
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "B",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 4,
            "r": 1
          },
          {
            "type": "B",
            "c": 0,
            "r": 3
          },
          {
            "type": "Q",
            "c": 4,
            "r": 0
          },
          {
            "type": "Q",
            "c": 0,
            "r": 4
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "B",
            "c": 4,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "Q",
            "c": 2,
            "r": 0
          },
          {
            "type": "B",
            "c": 3,
            "r": 4
          },
          {
            "type": "B",
            "c": 4,
            "r": 1
          },
          {
            "type": "P",
            "c": 3,
            "r": 0
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "B",
            "c": 1,
            "r": 4
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 4,
            "r": 2
          },
          {
            "type": "Q",
            "c": 3,
            "r": 2
          },
          {
            "type": "P",
            "c": 3,
            "r": 3
          },
          {
            "type": "P",
            "c": 4,
            "r": 3
          }
        ],
        "par": 5
      },
      {
        "cols": 5,
        "rows": 5,
        "pieces": [
          {
            "type": "K",
            "c": 1,
            "r": 3
          },
          {
            "type": "N",
            "c": 4,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 4
          },
          {
            "type": "K",
            "c": 4,
            "r": 1
          },
          {
            "type": "Q",
            "c": 0,
            "r": 2
          },
          {
            "type": "R",
            "c": 2,
            "r": 4
          }
        ],
        "par": 5
      }
    ]
  }
];
