// AUTO-GENERATED by scripts/generate-puzzles.js — do not edit by hand.
// LEVELS: solo studies (start + goal + BFS-verified par, with transform mode).
// DUO: arrangements of all 5 pieces for the 2-player carry-over bidding mode.
export const LEVELS = [
  {
    "id": "aprendiz",
    "name": "Aprendiz",
    "transforms": "none",
    "puzzles": [
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "par": 4,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "par": 3,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "par": 3,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "par": 3,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 4,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 4,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "par": 4,
        "transforms": "none"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "par": 3,
        "transforms": "none"
      }
    ]
  },
  {
    "id": "maestro",
    "name": "Maestro",
    "transforms": "rot",
    "puzzles": [
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 4,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "par": 3,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "par": 3,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "par": 5,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 3,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 0,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 4,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 2,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "par": 4,
        "transforms": "rot"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 0
          },
          {
            "type": "R",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 3,
        "transforms": "rot"
      }
    ]
  },
  {
    "id": "granmaestro",
    "name": "Gran Maestro",
    "transforms": "all",
    "puzzles": [
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "par": 4,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 0
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 2,
            "r": 1
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "par": 5,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "par": 4,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 0,
            "r": 2
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 1,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "par": 4,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 1,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 1,
            "r": 0
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 2,
            "r": 2
          }
        ],
        "par": 5,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 0,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 0
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 2
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 2
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 1
          },
          {
            "type": "K",
            "c": 1,
            "r": 0
          }
        ],
        "par": 5,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 2
          },
          {
            "type": "R",
            "c": 2,
            "r": 0
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 0,
            "r": 2
          },
          {
            "type": "K",
            "c": 0,
            "r": 0
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 2,
            "r": 2
          },
          {
            "type": "R",
            "c": 0,
            "r": 2
          },
          {
            "type": "B",
            "c": 1,
            "r": 1
          },
          {
            "type": "N",
            "c": 1,
            "r": 0
          },
          {
            "type": "K",
            "c": 2,
            "r": 1
          }
        ],
        "par": 5,
        "transforms": "all"
      },
      {
        "cols": 3,
        "rows": 3,
        "start": [
          {
            "type": "Q",
            "c": 1,
            "r": 1
          },
          {
            "type": "R",
            "c": 1,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 2
          },
          {
            "type": "N",
            "c": 0,
            "r": 0
          },
          {
            "type": "K",
            "c": 0,
            "r": 1
          }
        ],
        "goal": [
          {
            "type": "Q",
            "c": 0,
            "r": 1
          },
          {
            "type": "R",
            "c": 2,
            "r": 2
          },
          {
            "type": "B",
            "c": 2,
            "r": 0
          },
          {
            "type": "N",
            "c": 2,
            "r": 1
          },
          {
            "type": "K",
            "c": 0,
            "r": 2
          }
        ],
        "par": 5,
        "transforms": "all"
      }
    ]
  }
];

export const DUO = {
  "set": [
    "K",
    "Q",
    "R",
    "B",
    "N"
  ],
  "cards": [
    [
      {
        "type": "K",
        "c": 0,
        "r": 2
      },
      {
        "type": "Q",
        "c": 0,
        "r": 0
      },
      {
        "type": "R",
        "c": 2,
        "r": 0
      },
      {
        "type": "B",
        "c": 1,
        "r": 1
      },
      {
        "type": "N",
        "c": 1,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 1
      },
      {
        "type": "Q",
        "c": 2,
        "r": 0
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 2
      },
      {
        "type": "Q",
        "c": 1,
        "r": 2
      },
      {
        "type": "R",
        "c": 0,
        "r": 0
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 0,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 2
      },
      {
        "type": "Q",
        "c": 1,
        "r": 1
      },
      {
        "type": "R",
        "c": 0,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 2
      },
      {
        "type": "Q",
        "c": 0,
        "r": 0
      },
      {
        "type": "R",
        "c": 0,
        "r": 1
      },
      {
        "type": "B",
        "c": 2,
        "r": 0
      },
      {
        "type": "N",
        "c": 1,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 0
      },
      {
        "type": "Q",
        "c": 0,
        "r": 1
      },
      {
        "type": "R",
        "c": 0,
        "r": 2
      },
      {
        "type": "B",
        "c": 1,
        "r": 1
      },
      {
        "type": "N",
        "c": 1,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 0
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 0,
        "r": 1
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 1
      },
      {
        "type": "Q",
        "c": 2,
        "r": 2
      },
      {
        "type": "R",
        "c": 2,
        "r": 1
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 1,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 2
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 2,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 1,
        "r": 0
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 2
      },
      {
        "type": "Q",
        "c": 1,
        "r": 0
      },
      {
        "type": "R",
        "c": 2,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 1
      },
      {
        "type": "Q",
        "c": 1,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 0
      },
      {
        "type": "B",
        "c": 2,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 0
      },
      {
        "type": "Q",
        "c": 2,
        "r": 0
      },
      {
        "type": "R",
        "c": 0,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 0,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 0,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 0
      },
      {
        "type": "Q",
        "c": 2,
        "r": 0
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 1,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 0
      },
      {
        "type": "Q",
        "c": 1,
        "r": 2
      },
      {
        "type": "R",
        "c": 0,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 2,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 0,
        "r": 1
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 0
      },
      {
        "type": "Q",
        "c": 1,
        "r": 1
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 0
      },
      {
        "type": "Q",
        "c": 0,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 0
      },
      {
        "type": "Q",
        "c": 1,
        "r": 2
      },
      {
        "type": "R",
        "c": 2,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 0,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 2,
        "r": 0
      },
      {
        "type": "R",
        "c": 2,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 2
      },
      {
        "type": "Q",
        "c": 0,
        "r": 1
      },
      {
        "type": "R",
        "c": 2,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 1,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 0
      },
      {
        "type": "R",
        "c": 1,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 1,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 2,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 0
      },
      {
        "type": "Q",
        "c": 2,
        "r": 1
      },
      {
        "type": "R",
        "c": 0,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 1
      },
      {
        "type": "Q",
        "c": 1,
        "r": 0
      },
      {
        "type": "R",
        "c": 2,
        "r": 2
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 0
      },
      {
        "type": "Q",
        "c": 1,
        "r": 1
      },
      {
        "type": "R",
        "c": 2,
        "r": 0
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 1
      },
      {
        "type": "Q",
        "c": 2,
        "r": 1
      },
      {
        "type": "R",
        "c": 0,
        "r": 0
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 1,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 2
      },
      {
        "type": "Q",
        "c": 1,
        "r": 1
      },
      {
        "type": "R",
        "c": 0,
        "r": 1
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 1,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 0
      },
      {
        "type": "Q",
        "c": 1,
        "r": 1
      },
      {
        "type": "R",
        "c": 0,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 1,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 0
      },
      {
        "type": "Q",
        "c": 0,
        "r": 1
      },
      {
        "type": "R",
        "c": 1,
        "r": 1
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 0
      },
      {
        "type": "Q",
        "c": 2,
        "r": 2
      },
      {
        "type": "R",
        "c": 1,
        "r": 1
      },
      {
        "type": "B",
        "c": 2,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 1
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 0
      },
      {
        "type": "Q",
        "c": 0,
        "r": 1
      },
      {
        "type": "R",
        "c": 1,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 2,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 1,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 1
      },
      {
        "type": "R",
        "c": 2,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 0
      },
      {
        "type": "N",
        "c": 0,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 2
      },
      {
        "type": "Q",
        "c": 0,
        "r": 1
      },
      {
        "type": "R",
        "c": 1,
        "r": 1
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 1,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 1
      },
      {
        "type": "Q",
        "c": 0,
        "r": 0
      },
      {
        "type": "R",
        "c": 0,
        "r": 1
      },
      {
        "type": "B",
        "c": 2,
        "r": 2
      },
      {
        "type": "N",
        "c": 2,
        "r": 0
      }
    ],
    [
      {
        "type": "K",
        "c": 2,
        "r": 2
      },
      {
        "type": "Q",
        "c": 1,
        "r": 0
      },
      {
        "type": "R",
        "c": 0,
        "r": 0
      },
      {
        "type": "B",
        "c": 0,
        "r": 2
      },
      {
        "type": "N",
        "c": 1,
        "r": 2
      }
    ],
    [
      {
        "type": "K",
        "c": 0,
        "r": 1
      },
      {
        "type": "Q",
        "c": 1,
        "r": 2
      },
      {
        "type": "R",
        "c": 0,
        "r": 2
      },
      {
        "type": "B",
        "c": 2,
        "r": 0
      },
      {
        "type": "N",
        "c": 2,
        "r": 1
      }
    ]
  ]
};
