// Offline puzzle generator for "The Royal Study".
//
//   node scripts/generate-puzzles.js
//
// Each study has a start arrangement and a goal arrangement on a 3x3 board.
// Goals are produced by random-walking legal moves from a valid start, which
// guarantees reachability; the BFS solver then computes the true "par" (minimum
// number of moves). Output is deterministic (seeded RNG) so the committed set
// is stable across builds.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { createState, allMoves, applyMove, cloneState, isDark, isCentre } from '../src/game/engine.js';
import { solve } from '../src/game/solver.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- seeded PRNG (mulberry32) ----------------------------------------------
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const COLS = 3;
const ROWS = 3;

const LEVELS = [
  { id: 'aprendiz', name: 'Aprendiz', set: ['R', 'N', 'K'], walk: 5, parMin: 2, parMax: 4, seed: 11, want: 8 },
  { id: 'maestro', name: 'Maestro', set: ['Q', 'R', 'N', 'K'], walk: 7, parMin: 3, parMax: 6, seed: 22, want: 8 },
  { id: 'granmaestro', name: 'Gran Maestro', set: ['Q', 'R', 'B', 'N', 'K'], walk: 9, parMin: 4, parMax: 8, seed: 33, want: 8 },
];

const tmp = { cols: COLS, rows: ROWS };
const squares = [];
for (let r = 0; r < ROWS; r++) for (let c = 0; c < COLS; c++) squares.push({ c, r });

function validSquareFor(type, c, r, used) {
  if (used.has(`${c},${r}`)) return false;
  if (type === 'B' && !isDark(c, r)) return false;
  if (type === 'N' && isCentre(tmp, c, r)) return false;
  return true;
}

function randomStart(rand, set) {
  for (let attempt = 0; attempt < 500; attempt++) {
    const used = new Set();
    const pieces = [];
    let ok = true;
    for (const type of set) {
      const choices = squares.filter((s) => validSquareFor(type, s.c, s.r, used));
      if (!choices.length) { ok = false; break; }
      const s = choices[Math.floor(rand() * choices.length)];
      used.add(`${s.c},${s.r}`);
      pieces.push({ type, c: s.c, r: s.r });
    }
    if (ok) return pieces;
  }
  return null;
}

function randomWalk(rand, startPieces, steps) {
  const state = createState({ cols: COLS, rows: ROWS, start: startPieces });
  for (let i = 0; i < steps; i++) {
    const moves = allMoves(state);
    if (!moves.length) break;
    const m = moves[Math.floor(rand() * moves.length)];
    applyMove(state, m);
  }
  return state.pieces.map((p) => ({ type: p.type, c: p.c, r: p.r }));
}

const sig = (pieces) => pieces.map((p) => `${p.type}${p.c},${p.r}`).sort().join('|');

const levelsOut = [];
for (const level of LEVELS) {
  const rand = rng(level.seed);
  const found = [];
  const seen = new Set();
  let guard = 0;
  while (found.length < level.want && guard < 400000) {
    guard++;
    const start = randomStart(rand, level.set);
    if (!start) continue;
    const goal = randomWalk(rand, start, level.walk);
    if (sig(start) === sig(goal)) continue; // goal must differ from start

    const state = createState({ cols: COLS, rows: ROWS, start });
    const line = solve(state, goal);
    if (!line) continue;
    const par = line.length;
    if (par < level.parMin || par > level.parMax) continue;

    const id = `${sig(start)}=>${sig(goal)}`;
    if (seen.has(id)) continue;
    seen.add(id);
    found.push({ cols: COLS, rows: ROWS, start, goal, par });
  }
  console.log(`${level.name}: ${found.length} studies (tried ${guard})`);
  levelsOut.push({ id: level.id, name: level.name, puzzles: found });
}

const header = `// AUTO-GENERATED by scripts/generate-puzzles.js — do not edit by hand.
// Each study has start + goal arrangements on a 3x3 board; "par" is the
// BFS-verified minimum number of moves.
`;
const body = `export const LEVELS = ${JSON.stringify(levelsOut, null, 2)};
`;
const outPath = resolve(__dirname, '../src/game/puzzles.js');
writeFileSync(outPath, header + body);
console.log(`Wrote ${outPath}`);
