// Offline puzzle generator. Produces solvable solitaire-chess studies by
// random placement + solver verification, then writes src/game/puzzles.js.
//
//   node scripts/generate-puzzles.js
//
// Output is deterministic (seeded RNG) so the committed puzzle set is stable.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { createState } from '../src/game/engine.js';
import { solve } from '../src/game/solver.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- tiny seeded PRNG (mulberry32) -----------------------------------------
function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const LEVELS = [
  { id: 'aprendiz', name: 'Aprendiz', cols: 4, rows: 4, count: 4, seed: 101, want: 8 },
  { id: 'maestro', name: 'Maestro', cols: 5, rows: 5, count: 5, seed: 202, want: 8 },
  { id: 'granmaestro', name: 'Gran Maestro', cols: 5, rows: 5, count: 6, seed: 303, want: 8 },
];

// Weighted bag of piece types (pawns rarer; they are weak on tiny boards).
const BAG = ['Q', 'R', 'R', 'B', 'B', 'N', 'N', 'N', 'K', 'P'];

function randomPuzzle(rand, level) {
  const used = new Set();
  const pieces = [];
  for (let i = 0; i < level.count; i++) {
    let c, r, key;
    let type = BAG[Math.floor(rand() * BAG.length)];
    do {
      c = Math.floor(rand() * level.cols);
      r = Math.floor(rand() * level.rows);
      key = `${c},${r}`;
    } while (used.has(key));
    // Keep pawns off the top row so they always have a forward capture option.
    if (type === 'P' && r === level.rows - 1) r -= 1;
    used.add(`${c},${r}`);
    pieces.push({ type, c, r });
  }
  return { cols: level.cols, rows: level.rows, pieces };
}

function signature(p) {
  return p.pieces.map((x) => `${x.type}${x.c},${x.r}`).sort().join('|');
}

const levelsOut = [];
for (const level of LEVELS) {
  const rand = rng(level.seed);
  const found = [];
  const seen = new Set();
  let guard = 0;
  while (found.length < level.want && guard < 200000) {
    guard++;
    const puzzle = randomPuzzle(rand, level);
    const sig = signature(puzzle);
    if (seen.has(sig)) continue;
    const line = solve(createState(puzzle));
    if (!line) continue;
    // Skip studies whose only line is a trivial straight sweep by one piece.
    const movers = new Set(line.map((m) => m.pieceId));
    if (movers.size < 2 && level.count > 3) continue;
    seen.add(sig);
    found.push({ ...puzzle, par: line.length });
  }
  console.log(`${level.name}: ${found.length} puzzles (tried ${guard})`);
  levelsOut.push({ id: level.id, name: level.name, puzzles: found });
}

const header = `// AUTO-GENERATED by scripts/generate-puzzles.js — do not edit by hand.
// Each study is verified solvable; "par" is the minimum number of moves.
`;
const body = `export const LEVELS = ${JSON.stringify(levelsOut, null, 2)};
`;
const outPath = resolve(__dirname, '../src/game/puzzles.js');
writeFileSync(outPath, header + body);
console.log(`Wrote ${outPath}`);
